"""Page discovery, exclude lists, and markdown parsing helpers.

Both tools import from here so they always agree on which files are repository pages
and how to read headings / links out of them.
"""

from __future__ import annotations

import fnmatch
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from markdown_it import MarkdownIt

# Marker that the link-collection page (output of collect_links.py) carries so the
# verifier and collector both recognise it as generated and leave it alone.
GENERATED_BANNER = "AUTO-GENERATED by tools/collect_links.py"

# Page-type marker comment, e.g. ``<!-- page-type: case-study:failure -->``. The last such
# marker on a page declares its kind; absence means ``DEFAULT_PAGE_TYPE``. A type may carry an
# optional ``:subtype`` (e.g. case-study:success). The verifier uses the type to decide which
# structural checks apply (e.g. the core sections of a case-study page).
PAGE_TYPE_RE = re.compile(r"<!--\s*page-type:\s*([\w:-]+)\s*-->")
DEFAULT_PAGE_TYPE = "standard"

# Recognised page-type *base* names (the part before any ``:subtype``). A type whose base is
# not here is flagged by the verifier so typos in the marker don't slip through. Each maps to a
# template under ``templates/`` and, for some, extra structural checks in the verifier.
KNOWN_PAGE_TYPES = {"standard", "overview", "checklist", "risk-register", "case-study"}

# Directories that are never repository content (the tooling layer + VCS/dotdirs).
LAYER_EXCLUDE_DIRS = {"tools", "research", "research-toolkit", ".claude", ".git"}

# Root-level markdown files that belong to the tooling layer, not the repository.
LAYER_EXCLUDE_FILES = {"CLAUDE.md"}

# Repository pages that legitimately do NOT follow the page-template spine. The verifier
# skips these. Extendable from the CLI (`--exclude`) and the generated banner.
DEFAULT_TEMPLATE_EXCLUDES = [
    "README.md",
    "CONTRIBUTING.md",
    "templates/*.md",
]

_md = MarkdownIt("commonmark")


# --------------------------------------------------------------------------- #
# Discovery
# --------------------------------------------------------------------------- #
def default_repository_root() -> Path:
    """Repo root = parent of the ``tools/`` folder this package lives in."""
    return Path(__file__).resolve().parents[2]


# Subtrees that hold repository pages (besides root-level *.md). ``checklists`` and ``risk-register``
# hold the per-pillar cross-cutting artifacts; they are repository content and are verified too.
REPOSITORY_SUBDIRS = ("docs", "templates", "checklists", "risk-register")


def discover_pages(root: Path | str) -> list[Path]:
    """All repository pages: root-level ``*.md`` plus everything under the repository subdirs.

    Tooling-layer dirs/files are excluded. Result is sorted and deterministic.
    """
    root = Path(root).resolve()
    pages: list[Path] = []

    for path in sorted(root.glob("*.md")):
        if path.name in LAYER_EXCLUDE_FILES:
            continue
        pages.append(path)

    for subdir in REPOSITORY_SUBDIRS:
        base = root / subdir
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.md")):
            rel_parts = path.relative_to(root).parts
            if any(part in LAYER_EXCLUDE_DIRS for part in rel_parts):
                continue
            pages.append(path)

    return pages


def relpath(path: Path | str, root: Path | str) -> str:
    """POSIX path of *path* relative to the repository *root* (for messages/links)."""
    return Path(path).resolve().relative_to(Path(root).resolve()).as_posix()


def has_generated_banner(path: Path | str) -> bool:
    try:
        head = Path(path).read_text(encoding="utf-8").splitlines()[:5]
    except (OSError, UnicodeDecodeError):
        return False
    return any(GENERATED_BANNER in line for line in head)


def is_template_excluded(
    path: Path | str,
    root: Path | str,
    extra: Iterable[str] = (),
) -> bool:
    """True if the page is exempt from template/spine checks."""
    rel = relpath(path, root)
    for pattern in [*DEFAULT_TEMPLATE_EXCLUDES, *extra]:
        if rel == pattern or fnmatch.fnmatch(rel, pattern):
            return True
    return has_generated_banner(path)


# --------------------------------------------------------------------------- #
# Parsing
# --------------------------------------------------------------------------- #
@dataclass
class Heading:
    level: int
    text: str
    line: int  # 1-based


@dataclass
class Link:
    url: str
    text: str
    line: int  # 1-based
    section: str  # nearest preceding H2 title, "" if none


@dataclass
class ParsedPage:
    path: Path
    root: Path
    text: str
    lines: list[str] = field(default_factory=list)
    headings: list[Heading] = field(default_factory=list)
    links: list[Link] = field(default_factory=list)

    @property
    def rel(self) -> str:
        return relpath(self.path, self.root)


def _inline_text(token) -> str:
    if token is None:
        return ""
    if token.children:
        return "".join(c.content for c in token.children if c.type in ("text", "code_inline"))
    return token.content or ""


def parse(path: Path | str, root: Path | str) -> ParsedPage:
    path = Path(path).resolve()
    root = Path(root).resolve()
    text = path.read_text(encoding="utf-8")
    tokens = _md.parse(text)

    headings: list[Heading] = []
    links: list[Link] = []
    section = ""

    for i, tok in enumerate(tokens):
        if tok.type == "heading_open":
            inline = tokens[i + 1] if i + 1 < len(tokens) else None
            title = _inline_text(inline).strip()
            line = (tok.map[0] + 1) if tok.map else -1
            headings.append(Heading(int(tok.tag[1]), title, line))
            if tok.tag == "h2":
                section = title
        elif tok.type == "inline" and tok.children:
            line = (tok.map[0] + 1) if tok.map else -1
            kids = tok.children
            for j, child in enumerate(kids):
                if child.type != "link_open":
                    continue
                href = child.attrGet("href") or ""
                label = ""
                for k in range(j + 1, len(kids)):
                    if kids[k].type == "link_close":
                        break
                    label += kids[k].content or ""
                links.append(Link(href, label.strip(), line, section))

    return ParsedPage(
        path=path,
        root=root,
        text=text,
        lines=text.splitlines(),
        headings=headings,
        links=links,
    )


def page_type(page: ParsedPage) -> str:
    """Declared page type from the ``<!-- page-type: X -->`` marker.

    Uses the last marker on the page (the marker is expected to be the final line) and
    falls back to ``DEFAULT_PAGE_TYPE`` when none is present.
    """
    found = DEFAULT_PAGE_TYPE
    for line in page.lines:
        m = PAGE_TYPE_RE.search(line)
        if m:
            found = m.group(1).lower()
    return found
